build:
	haxe clippingdemo.hxml

swfmill:
	/usr/local/src/swfmill-svn/src/swfmill simple lib.xml lib.swf

mxmlc:
	/opt/flex_3/bin/mxmlc -default-frame-rate 70 -default-background-color "#ffffff" -default-size 500 300 -use-network=false  -compiler.source-path ../../sandy.as3 -output clippingdemo_as3.swf ClippingDemo.as
